name: custom_gs
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - plyfile
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - tqdm
  - matplotlib
  - ipykernel
  - ipywidgets
  - pip:
      - rich
      - icecream
      - submodules/depth-diff-gaussian-rasterization
      - submodules/simple-knn
